### ISSUE TITLE
Create entry in wiki history on diagram update

### ISSUE THREAD

**Issue by xanadiu** [mikitex70/redmine_drawio#100]
(This is a proposal for an enhancement)

After editing a diagram which is embedded in a wiki page, the content of the wiki page changes by referencing to the next version of the attached diagram. This is visible in the history of the wiki page by comparing the two affected page versions.

I would like to request an enhancement: The history also offers a comment attribute, which can be be submitted with any update of the wiki page. I think it could be useful to add a comment about the updated diagram. To avoid localisation problems, an easy approach could be something like "diagram_1.svg -> diagram_2.svg".

**Comment by mikitex70** [comment]
Hi @xanadiu, your suggestion is now implemented in the @1.1.4@ version.
