### ISSUE TITLE
Display a warning when reloading or closing an editor page

### ISSUE THREAD

**Issue by xanadiu** [mikitex70/redmine_drawio#101]
I wonder if it is possible to prevent the user from accidentally reloading or closing the diagram editor when there are unsaved changes. I know that some browsers ask for confirmation when reloading or closing a page with a form that contains user-entered data. Maybe there is a hook to use this while editing. Or would that be a request for the diagram editor and out of scope for this plugin?

**Comment by mikitex70** [comment]
Hi @xanadiu, I've done some test and when clicking in the `Exit` button of the diagram editor a dialog will popup asking confirmation to discard changes.
I've also tried a whole reload of the page (Redmine URL, but the diagram editor is shown) and the the dialog pops up correctly.
My tests were done with Firefox.
Have you some use case where the dialog does not appear?

**Comment by xanadiu** [comment]
Hi @mikitex70, sorry for being lazy in not specifying the browser information...

I am working on a Mac (macOS 11.6) and discovered these behaviours (after altering and not explicitly saving the diagram):

Web browser|Reload the window|Close the window|Click on `Exit`
--|--|--|--
Safari 15.0|No warning<br />Diagram editor disappears<br />Redmine content is shown<br />Changes are lost|No warning<br />Window is closed<br />Changes are lost|Alert (website specific) "All changes will be lost!" with `Discard Changes` and `Cancel` options  √
Firefox 92.0.1|Alert (browser specific) informs user about unsaved changes √|Alert (browser specific) informs user about unsaved changes √|Alert (website specific) √
Chrome 92.0.4515|Alert (browser specific) informs user about unsaved changes √|Alert (browser specific) informs user about unsaved changes √|Alert (website specific) √

So the problem seems to correlate with Safari...

**Comment by mikitex70** [comment]
The check for unsaved diagram is done fully in the diagram editor.
Maybe you can try to open an issue on [drawio](https://github.com/jgraph/drawio/issues).
Before that, do a simple check: go to https://app.diagrams.net/, draw a simple diagram and check with Safari and another browser if it asks for unsaved data.

**Comment by mikitex70** [comment]
No more feedback, closing this issue.
