### ISSUE TITLE
Redmine 5.0 Support

### ISSUE THREAD

**Issue by dktcoding** [mikitex70/redmine_drawio#109]
Hi there! 

I was wondering if support for Redmine 5.0 is planned.

Regards

**Comment by mikitex70** [comment]
Not yet testes, but it should work.
Give me some day, I will do some check and update the plugin requirements.

**Comment by dktcoding** [comment]
Thanks!

**Comment by mikitex70** [comment]
I am working on it, but it will take me some time as the transition to Rails 6 is not that easy, I need to figure out how to adapt some parts of the code.

**Comment by mikitex70** [comment]
Fixed by PR #110, release in version `v1.4.0`.
Closing this issue.
