### ISSUE TITLE
Error saving diagram: Not Found

### ISSUE THREAD

**Issue by AdrianAntunez** [mikitex70/redmine_drawio#11]
Hi,

With redmine-3.3.1 and redmine_drawio version v0.4.0 (API enabled). I receive the following error after editing a diagram in a Wiki page:

> Error saving diagram:
> Not Found

The problem goes off if I checkout into a v0.3.2 tag. Meanwhile I will use 0.3.2 version. 

If you need any additional info, please, let me know.

**Comment by mikitex70** [comment]
I've checked ``v0.4.0`` and on my test server works fine.
What macro are you using, ``drawio``, ``drawio_attach`` or ``drawio_dmsf``?
In what kind of pages, issues or wiki pages?

The error ``Not Found`` (HTTP 404) is raised from the ``dmsf`` plug-in when the WebDAV capabilities aren't enabled (see the ``README``, section ``drawio_dmsf macro``). But ``v0.3.2`` works fine for you so it is strange.
Plug-in version ``0.4.0`` should report the message ``Make sure WebDAV capabilities of DMSF module is enabled``; the message ``Not found`` comes from the version ``0.3.2`` of the plug-in so it seems the new Javascript was not downloaded. Please try to clean the browser cache, maybe this is the problem.

**Comment by AdrianAntunez** [comment]
Hi mikitex70, first of all thanks for answering!

It happens in wiki pages.

It happens when using the `drawio_attach` macro.

I also tested the `{{drawio(activity.xml)}}`, it raises another message: "Diagram attachment missing or not is a text file"

I double checked, I have `REST` API enabled. I do not have WebDAV API enabled because I'm not using `dmsf`.

I also wiped out the cookies as well as browser cache with no luck. 

Just to complete the testing, I have added both `drawio` and `drawio_attach` in a issue response with the message: "«Drawio diagrams are available only in issues and wiki pages»".

It does not work either in the description of a new issue (it does not get translated to something, just shows the original command: `{{draw_io (test.xml}}`.

**Comment by mikitex70** [comment]
Hi Adrian, it took me time but I think to have fixed the problem, try to checkout the develop branch.
I've also added the support for using the macros in issue notes, which weren't handled. The drawio_attach macro isn't working completely because of missing Redmine APIs for issue notes, so you need to use the other two macros.

**Comment by AdrianAntunez** [comment]
You're right mikitex70.

Now it works like a charm! Thank you so much!! ;)
