### ISSUE TITLE
Redmine 5.x issue

### ISSUE THREAD

**Issue by whotopia** [mikitex70/redmine_drawio#112]
Have tried to add a simple 

`{{drawio_attach(myDiagram)}}`

to Redmine 5.x wiki.   

To this I get the error:

**`Error executing the drawio_attach macro (undefined method `strip_non_filename_chars' for #<ActionView::Base:0x00000000021098>)
`**
in red on the wiki page.

Can someone help?

**Comment by mikitex70** [comment]
Hi @whotopia, I'll check the sources, maybe during the port on Redmine 5 I missed something.

**Comment by mikitex70** [comment]
I've done a quick test and the macro `drawio_attach` seems working fine, and the usages of `strip_non_filename_chars` are correctly fixed for Redmine 5.
Are you sure that the sources of the plugin are correct? Can you try to re-download the plugin again?

**Comment by whotopia** [comment]
> I've done a quick test and the macro `drawio_attach` seems working fine, and the usages of `strip_non_filename_chars` are correctly fixed for Redmine 5. Are you sure that the sources of the plugin are correct? Can you try to re-download the plugin again?

It is weird.   So I downloaded your redmine_drawio-1.4.0.tar.gz release file, deployed,  and that one works fine.   I'm relieved for this, but will do a bit more digging on a non-production system. Might it be an interaction with another plugin?    I'll let you know.  For now closing this.
