### ISSUE TITLE
Toolbar button is shown in WYSIWYG editor (plugin) but not in Redmine markdown editor

### ISSUE THREAD

**Issue by CSCSxx** [mikitex70/redmine_drawio#119]
System:
Redmine 5.0.2
Text formatter: Common Markdown (Github flavored)
Plugin: https://github.com/taqueci/redmine_wysiwyg_editor

Since switching to Redmine 5.x, we have been using the WYSIWYG editor instead of the CK editor as before. So the only option we had was to switch the text formatter to Common Markdown, as that was the only one left that rendered the CK editor's HTML elements reasonably correctly.

We have now installed drawio and it works so far, but:
* the toolbar button is not displayed in the common mardown editor
* The buttons are displayed in WYSIWYG, but have no function (no error message/simply no reaction)

Would be great if it works in WYSIWYG Editor!!!

**Comment by mikitex70** [comment]
Hi @CSCSxx, the `1.4.3` version should fix your issue.
The toolbar buttons now are working in the native and in the WYSIWYG editor.
Thanks for reporting it.

**Comment by CSCSxx** [comment]
> Hi @CSCSxx, the `1.4.3` version should fix your issue. The toolbar buttons now are working in the native and in the WYSIWYG editor. Thanks for reporting it.

Hello,
First of all, many thanks for the super fast response and processing (really cool!).
I migrated to the new version and lo and behold, the toolbar buttons appear in the native editor and work as well.
However, they no longer appear in the plugin editor

**Comment by mikitex70** [comment]
Hi @CSCSxx, you were right.
The problem was a polling timeout in detecting when the TinyMCE editor is initialized: on recent (fast) machines the code was initializing too fast.
I've reduced the timeout, now it seems to work find; try downloading the `develop` branch and let me know if it works.

**Comment by CSCSxx** [comment]
Ok, I installed the developer version.
In most cases it works now, however I can keep reproducing a scenario where it doesn't work:
* Edit an existing issue
* Edit issue description (first entry).
* In this text editor field, the toolbar buttons appear in the native editor but not in the plugin editor
* In the lower text editor (comment field), the buttons appear in both editors

However, this is such a minimal error - if you know it ;)

Thanks again!

**Comment by mikitex70** [comment]
Hi @CSCSxx, try to pull from the 'development' branch, I fixed the initialization of the toolbar and now the buttons should appear in every editor.
I made some corrections in the macro insertion code as well, since sometimes the value was not saved after the change.

**Comment by CSCSxx** [comment]
Cool, it works.
No matter what I wildly click back and forth, the buttons stay there :)
