### ISSUE TITLE
Plugin configure section to choose drawio server

### ISSUE THREAD

**Issue by AdrianAntunez** [mikitex70/redmine_drawio#12]
Hi,

My company takes privacy very seriously. For that reason, we have deployed a private drawio server in order to use it only internally without Internet access.

I have achieved to make it work modifying assets/javascripts/drawioEditor.js, concretely:

`image.setAttribute('src', '//www.draw.io/images/ajax-loader.gif');`
and
`iframe.setAttribute('src', 'https://www.draw.io/?embed=1&ui=atlas&spin=1&modified=unsavedChanges&proto=json');`

Maybe, you would like to make that feature available to everyone using the configure plugin section. It is just an idea.

Cheers and keep on with your great work!!

**Comment by mikitex70** [comment]
Hi Adrian,
that's something I'd already planning to implement; using a local installation of drawio would speed-up resource fetching, specially for the ``drawio`` macro which renders diagrams every time a page is consulted.
I think I could implement it in the weekend, maybe a test release would be ready for the next monday.

**Comment by AdrianAntunez** [comment]
Yeah it would be a performance boost! I will test it ASAP you release the code ;)

**Comment by mikitex70** [comment]
Hi Adrian, I've implemented your request. Can you give a try with the develop branch?
Also, look in the README for a section on building the draw.io war file, maybe you need to apply the patch included in the plugin sources.

**Comment by AdrianAntunez** [comment]
I'm a bit busy those days, I will let you know ASAP I test it. Thank you so much! ;)

**Comment by mikitex70** [comment]
No feedbacks in the last months.
I close this issue as seems the are no other problems.
Feel free to open a new issue for the latest version of the plugin, which will be released soon.
