### ISSUE TITLE
Failed to execute 'addEventListener' on 'EventTarget': parameter 2 is not of type 'Object'.

### ISSUE THREAD

**Issue by sstidl** [mikitex70/redmine_drawio#120]
Is #105 here again?

using 

`{{drawio_attach(test_1.xml,hilight=#0000ff)}}`

i get 
_Failed to execute 'addEventListener' on 'EventTarget': parameter 2 is not of type 'Object'._

My codebase is: 
tags/v1.4.2
since master or v1.4.3 is not working with our Environment:
Environment:
```
  Redmine version                4.2.7.stable
  Ruby version                   2.7.5-p203 (2021-11-24) [x86_64-linux-gnu]
  Rails version                  5.2.8
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.13.0
  Mercurial                      5.3.1
  Cvs                            1.12.13
  Bazaar                         3.0.2
  Git                            2.36.1
  Filesystem                     
Redmine plugins:
  additionals                    3.0.5.2
  clipboard_image_paste          1.13
  computed_custom_field          1.0.7
  external_links_in_new_window   0.9
  redmine_agile                  1.6.4
  redmine_banner                 0.3.4
  redmine_checklists             3.1.21
  redmine_drawio                 1.4.2
  redmine_issue_templates        1.1.0
  redmine_issues_tree            0.0.14
  redmine_resources              1.0.7
  redmine_slack                  0.2
  redmine_theme_changer          0.6.0
```

**Comment by mattomis** [comment]
I am seeing the same issue with Drawio plugin 1.4.2.
`Environment:
  Redmine version                4.2.3.stable
  Ruby version                   2.5.9-p229 (2021-04-05) [x86_64-linux-gnu]
  Rails version                  5.2.6
  Environment                    production
  Database adapter               Mysql2
  Database timezone              CEST
  ActiveRecord timezone          local
  App timezone                   UTC
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.10.6
  Cvs                            1.12.12
  Git                            2.35.3
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.6.4
  redmine_drawio                 1.4.2
  redmine_home_page_redirector   1.0.0
  redmine_mentions               0.1.1
  redmine_more_filters           1.4.4
  redmine_my_page_paginations    1.0.2
  redmine_remote_revision_url    0.3.2
  redmine_tint_issues            1.2.1
  redmine_wysiwyg_editor         0.23.0
  that_issue_reply_button        0.0.1`

**Comment by mattomis** [comment]
I have the same result using for issue text:
 `# {{drawio_attach(test.xml,size=800,zoom=true,lightbox=true,hilight=#0000ff)}}`

I see in the issue description:
_Failed to execute 'addEventListener' on 'EventTarget': parameter 2 is not of type 'Object'._

Environment:
  Redmine version                4.2.3.stable
  Ruby version                   2.5.9-p229 (2021-04-05) [x86_64-linux-gnu]
  Rails version                  5.2.6
  Environment                    production
  Database adapter               Mysql2
  Database timezone              CEST
  ActiveRecord timezone          local
  App timezone                   UTC
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.10.6
  Cvs                            1.12.12
  Git                            2.35.3
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.6.4
  redmine_drawio                 1.4.2
  redmine_home_page_redirector   1.0.0
  redmine_mentions               0.1.1
  redmine_more_filters           1.4.4
  redmine_my_page_paginations    1.0.2
  redmine_remote_revision_url    0.3.2
  redmine_tint_issues            1.2.1
  redmine_wysiwyg_editor         0.23.0
  that_issue_reply_button        0.0.1

**Comment by pkunduCere** [comment]
Same problem here
Environment:
  Redmine version                4.2.5.stable
  Ruby version                   2.7.5-p203 (2021-11-24) [x86_64-linux-gnu]
  Rails version                  5.2.6.3
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
Redmine plugins:
  redmine_drawio                 1.4.2

**Comment by mikitex70** [comment]
You were right, it is the same problem.
A refactor was made in the file 'viewer-static.min.js' and this prevented the correct application of the patch for the addition of the editing button. 
Try downloading the version from the 'develop' branch, it should work properly now.

**Comment by sstidl** [comment]
Thank you, commit:c4a4da053a7200b58d2d645e571889fa85e62199 fixes this.
