### ISSUE TITLE
Drawio enables math mode

### ISSUE THREAD

**Issue by ksingvo** [mikitex70/redmine_drawio#125]
When Plugin redmine_drawio is enabled, I see unwanted math formated symbols:

The description contains this text:
```
Cable-precheck Test:
> 1. `c.generic_test_check.get_names() #Display all test names`
```

and leads to this:
![image](https://github.com/mikitex70/redmine_drawio/assets/24297496/6513a6b7-e9eb-4cb5-ae7d-bb91b076e7f2)

**Comment by mikitex70** [comment]
Hi @ksingvo, I've done some check and yes, the plugin loads the [MathJax](https://www.mathjax.org/) library used by DrawIO.
But the library is optional (and usually disabled), simply disable its loading in the plugin configuration panel (`Adminitrations` -> `Plugins`  -> `Redmine Drawio plugin` -> `Configuration`.

**Comment by mikitex70** [comment]
I've found a way that can be used to disable the Mathjax rendering, enclose the text in a `div` with class `no-mathjax`.
Your example become:
```
Cable-precheck Test:<div class="no-mathjax">
> 1. `c.generic_test_check.get_names() #Display all test names`
</div>
```

Not elegant but can be used to disable Mathjax as required.

**Comment by ksingvo** [comment]
Yes, wow. Never hat such a solution in mind.

That's a good working solution for me.
--> Issue can be closed with solution given.

Thank you.
