### ISSUE TITLE
DrawIO URL parameters are not taking effect

### ISSUE THREAD

**Issue by canadabri** [mikitex70/redmine_drawio#128]
I have my own hosted DrawIO.  When I pass URL paramters such as: ` https://myurl.com:8443/draw/?stealth=1`   The DrawIO comes up without any storage options except Device.   This is expected behavior based on the documented URL parameters for DrawIO seen here : [Click Here](https://www.drawio.com/doc/faq/supported-url-parameters)

If I use that URL in the plugin configuration (i.e. `//myurl.com:8443/draw/?stealth=1`  )   the URL parameters are ignored.  

My environment is a network without Internet access, so I am wanting to disable certain DrawIO options.  

Is this possible?

**Comment by mikitex70** [comment]
Hi @canadabri, I've released the `1.4.7` version which fixes your issue. Try it.

**Comment by canadabri** [comment]
Works perfect!  thank you!
