### ISSUE TITLE
Cannot install draw.io plugin on redmine 3.3.1

### ISSUE THREAD

**Issue by cryshader** [mikitex70/redmine_drawio#13]
Hi! 
We've updated redmine to version 3.3.1.stable and cannot install redmine_drawio plugin.
It worked well on redmine 3.2.3.
At the start hooks could not be found, 
`LoadError: no such file to load -- hooks/view_hooks`
so we changed init.rb:
`require_dependency 'hooks/view_hooks'
require_dependency 'hooks/macro_dialog'`
to absolute path:
`require_dependency '/full/path/to/redmine/plugins/redmine_drawio/lib/hooks/view_hooks'
require_dependency '/full/path/to/redmine/plugins/redmine_drawio/lib/hooks/macro_dialog'`
After that another error appeared. Please have a look at log attached.
[production.zip](https://github.com/mikitex70/redmine_drawio/files/699407/production.zip)
Our current system spec:
OS: CentOS 7.0
redmine: 3.3.1.stable
ruby: 2.3.0-p0
rails: 4.2.7.1

**Comment by mikitex70** [comment]
What OS are you using, Windows or Linux?
I'm unable to reproduce your error, the only difference is the ruby version, mine is 2.1.9p490.
I will try to upgrade a docker container with your version of Ruby to see if is this the problem.

**Comment by cryshader** [comment]
Hi, we've updated our issue with OS, it's CentOS 7.0

**Comment by amenk** [comment]
It's EasyRedmine, right? Cause i am seeing "easy_instant_messages" in the log... Which easyredmine version is it? @cryshader

**Comment by amenk** [comment]
Are you using the develop or master branch? The develop branch (only) works well with Easy Redmine 2016.05.07 here ...
