### ISSUE TITLE
Support *.drawio file ending

### ISSUE THREAD

**Issue by liaham** [mikitex70/redmine_drawio#131]
Hi @mikitex70,

I recently found out that it is possible to integrate outside of Redmine created drawio files into Redmine with your plugin. For doing so, you need to rename the file with `*.drawio`  ending to `*.xml`.  It will be identified and you can continue to draw your items.

Unfortunately, it is not possible to initially save drawio files as `*.xml`. When I chose this ending the file will be listed with `*.dawio` ending nevertheless.  I need to change the file ending manually in a second step.

Do you think it is possible to support `*.drawio` file endings in your plugin? 

Then it would be much easier to integrate existing drawio files in Redmine.

Best Regards,
@liaham

**Comment by mikitex70** [comment]
Hi @liaham, in the `develop` branch I pushed a preliminary version that implements your request.
Now the `drawio` extension in allowed, and when creating a new diagram the diagram type`DRAWIO` is available.
I'm not sure about this new option, maybe it's better to handle the `drawio` extension internally, adding the extension to the filename only if it's not `xml` nor `drawio`. What do you think about?

**Comment by liaham** [comment]
Hi @mikitex70,

I am happy to see that you have been started with this feature. Thank you! :)

I would prefer the `drawio` extension as a further option as you implemented in your  preliminary version. This would make it more transparent for a user about what is supported and what not. 

I tested the preliminary version with these workflows:

### drawio_attach macro

✅ Upload `drawio` file on wiki page.
✅ Click wikitoolbar icon for `drawio_attach` macro.
✅ Select `drawio` file ending, enter file name and other options.
✅ Save wiki page.
✅ Open integrated drawing, change it and save.
✅ See changes on wiki page.
❌ Download changed file. ❗<-- Is not working right now since there won't be a new file version saved when saving changes in drawio UI.

### drawio_dmsf macro

✅ Upload `drawio` file in dms of the current project.
✅ Navigate to wiki page in the same project and click wikitoolbar icon for `drawio_dmsf` macro.
✅ Select `drawio` file ending, enter file name and other options.
✅ Save wiki page.
❌ Open integrated drawing, change it and save. ❗<-- Not possible since wiki page shows macro error with `(wrong number of arguments (given 1, expected 0))`.
❌ See changes on wiki page.
❌ Download changed file. 

Let me know when there is something else I can help with! 

Best Regards,
@liaham

**Comment by mikitex70** [comment]
Try the new version from the `develop` branch, I hope I have solved all the problems.

**Comment by mikitex70** [comment]
Released in version @v1.4.8@.
Thanks for your work.
