### ISSUE TITLE
drawio_dmsf (wrong number of arguments (given 1, expected 0))

### ISSUE THREAD

**Issue by jmtemmos** [mikitex70/redmine_drawio#133]
Hello.

I got an error when trying to edit a drawio_dmsf diagram.
Create works fine, but then, when trying to edit, I got a macro error : drawio_dmsf (wrong number of arguments (given 1, expected 0))

only found workaround is to use drawio_attach instead

Thanks for your help

>Environment:
  Redmine version                5.0.5.stable.22130
  Ruby version                   3.0.0-p0 (2020-12-25) [x86_64-linux]
  Rails version                  6.1.7.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
Redmine settings:
SCM:
  Subversion                     1.14.1
  Mercurial                      6.1.1
  Cvs                            1.12.13
  Bazaar                         3.2.1
  Git                            2.34.1
  Filesystem                     
Redmine plugins:
  additional_tags                3.0.9
  additionals                    3.0.9
  redmine_checklists             3.1.22
  redmine_dashboard              2.12.3
  redmine_db                     3.0.9
  redmine_dmsf                   3.1.2
  redmine_drawio                 1.4.7
  redmine_extended_watchers      5.0.2
  redmine_impersonate            2.0.0
  redmine_leaflet_maps           0.2
  redmine_privacy_terms          1.0.6
  redmine_web_forms              1.0.0
  redmine_wktime                 4.7

**Comment by liaham** [comment]
Hi @jmtemmos ,

Thank you for your report.

The error you described is already fixed in the develop branch. Please wait until a new version will be released by @mikitex70 .

@liaham

**Comment by jmtemmos** [comment]
> Hi @jmtemmos ,
> 
> Thank you for your report.
> 
> The error you described is already fixed in the develop branch. Please wait until a new version will be released by @mikitex70 .
> 
> @liaham

Great ! I'll pull the dev version in the meantime

Thanks a lot

**Comment by mikitex70** [comment]
The new version @v1.4.8@ has now the fix.
