### ISSUE TITLE
Error executing drawio_attach macro

### ISSUE THREAD

**Issue by vjankovsky** [mikitex70/redmine_drawio#137]
If the diagram contains any language-dependant characters, it will throw the following Error.
Here is the example for Czech localization:
Chyba při vykonávání drawio_attach makra ("\xC4" from ASCII-8BIT to UTF-8)
Translation
Error executing drawio_attach macro ("\xC4" from ASCII-8BIT to UTF-8)

How to replicate:
1) Insert the draw.io diagram into the wiki page. 
2) Save the wiki page
3) Edit the diagram using the pencil - draw.io
4) Write local character anywhere in the diagram ie. ě, š, č, á..
5) Save the diagram and go back to Redmine
6) Refresh the wiki page with the inserted diagram
(tested with Redmine 5.0.1.stable)
I would appreciate any advice you could give me on handling this issue.

**Comment by mikitex70** [comment]
Hi @vjankovsky, sorry for the delay.
I think I've fixed this issue in the `development` branch; could you give it a try?
I think I should have enough time over the weekend to release the new version.

**Comment by vjankovsky** [comment]
hi @mikitex70 , sorry for the delay with testing. 
I've just tested the development branch version and YES, it's fixed!
Thank you so much - this will help us a lot.
