### ISSUE TITLE
Problem install

### ISSUE THREAD

**Issue by julianram** [mikitex70/redmine_drawio#14]
Error:

/var/lib/gems/1.9.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require': /srv/redmine-3.0/plugins/redmine_drawio/init.rb:47: invalid multibyte char (US-ASCII) (SyntaxError)

Solution: write head init.rb

"# encoding: UTF-8"

Regards,

**Comment by mikitex70** [comment]
Thanks for you suggestion  julianran.
I've just released a new version, with your fix and some other changes.
