### ISSUE TITLE
Collaborative editting diagrams - Multiple per-user files saved instead

### ISSUE THREAD

**Issue by jmygt** [mikitex70/redmine_drawio#143]
Hello,

Using Drawio plugin version 1.5.0 in Redmine version  5.1.3.stable.
Using `//embed.diagrams.net` as the Draw.io service URL.

Single users can edit and save diagrams as expected (actual .drawio figures). 

However, we were expecting to be able to collaboratively edit the diagrams (that is, two or more users simultaneously editing the same diagram). What happens instead is that each user seems to be editing its own copy of the original diagram, which then becomes saved in a new version of the diagram. So if two users edit the same diagram, at the end of the editing there are two more files with different diagrams, each with the changes independently made by each user.

We were expecting collaborative editing to work on the basis that it works in NextCloud using [Draw.io's integration app](https://apps.nextcloud.com/apps/drawio) when `embed.diagrams.net` is used (see its [info section on its github project](https://github.com/jgraph/drawio-nextcloud?tab=readme-ov-file#info), although autosave is expected to be enabled also...)

So, is collaborative edition supported in Redmine? And if so, how to properly enable it?

BR,
J.

**Comment by mikitex70** [comment]
Hi @jmygt, sorry but this is not supported by Redmine.
Editing a diagram is similar to edit a wiki page or an issue: can you collaborative edit the same wiki page at the same time with other users? No, it is something that Redmine does not support and. maybe, it is beyond the scope of Redmine.

If you need to collaborative edit the same diagram with other users, you must choose another tool. When the diagram is stable you can upload it to Redmine (as XML o PNG) and then it is possible to modify it inside Redmine (if needed). But only one user at a time can modify it.

**Comment by jmygt** [comment]
OK, thanks for the clarification, and for the plugin, of course.
