### ISSUE TITLE
redmine_drawio crashes in redmine v5.0.4

### ISSUE THREAD

**Issue by StefanPofahl** [mikitex70/redmine_drawio#144]
My installation is quite new, beside `redmine_drawio` no plugins installed.
It is set up according to following procedure: [Redmine Installation on Debian](https://wiki.debian.org/Redmine).
Webserver is `Apache2` and database is `postgreSQL`.
To install the package I did:
```
cd /usr/share/redmine/lib/plugins
git clone https://github.com/mikitex70/redmine_drawio.git
```
One question, - where is the following variable defined: `$REDMINE_HOME`?

I was not sure how to restart redmine, I wonder if the following is still state of the art to restart redmine:
```
touch /usr/share/redmine/tmp/restart.txt
```
source: [How to Restart Redmine?](https://www.redmine.org/boards/2/topics/48967)

For debugging purposes I included the option:
```
PassengerFriendlyErrorPages On

```
inside: `/etc/apache2/sites-available/redmine.conf`

The first two lines of the passenger debug information is:

> uninitialized constant Redmine::Plugin (NameError)
>   /usr/share/redmine/lib/plugins/redmine_drawio/init.rb:3:in `block in <top (required)>'
> 
Please let me know what I can do, to track down the issue.

**Comment by mikitex70** [comment]
`$REDMINE_HOME` may not be defined, depending on the installation.
It must contain the path where Redmine is installed, usually `/var/www/html/redmine`.

**Comment by mikitex70** [comment]
@StefanPofahl, the `REDMINE_HOME` folder usually have at least the following contents:
* `app`, `config`, `plugins` and `lib` directories
* `Gemfile`, `Gemfile.lock`, `Rakefile` and `README.rdoc` files

There are many other files and folder, but ad least the `README.rdoc` which mentions `Redmine` should be there.
From you wrote I think your `REDMINE_HOME` should be `/usr/share/redmine`.

From your first post I see you installed the plugin in `/usr/share/redmine/lib/plugins`: this is wrong, plugins should be installed in `/usr/share/redmine/plugins` (see the [Redmine documentation](https://www.redmine.org/projects/redmine/wiki/Plugins); the `REDMINE_HOME` is called `RAILS_ROOT`).

**Comment by StefanPofahl** [comment]
@mikitex70 
Thanks a lot! :-) 
The definition of `REDMINE_HOME` was not easy (for me not possible) to find.
Good to know, that the folder is not present, after installation of `redmine` in the _Debian_ style
and may need to be created.
