### ISSUE TITLE
[Support] Compatibility with Easy Redmine

### ISSUE THREAD

**Issue by amenk** [mikitex70/redmine_drawio#18]
After installation of the plugin, the easy redmine install does not start anymore.

Can you give me some pointers on how to debug?

`Message from application: No such file to load -- hooks/view_hooks (LoadError)`

<details>

	App 21245 stdout: 
	[ 2017-04-27 13:19:29.7182 19866/7f28923eb700 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /srv/easyproject/public_html: An error occurred while starting up the preloader.
	  Error ID: 828d7f4b
	  Error details saved to: /tmp/passenger-error-ippfcO.html
	  Message from application: No such file to load -- hooks/view_hooks (LoadError)
	  /usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	  /usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
	  /usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	  /usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	  /usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:360:in `require_or_load'
	  /usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:317:in `depend_on'
	  /usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:233:in `require_dependency'
	  /srv/easyproject/public_html/plugins/redmine_drawio/init.rb:6:in `<top (required)>'
	  /usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	  /usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
	  /usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	  /usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	  /srv/easyproject/public_html/plugins/easyproject/init.rb:385:in `load_plugin_init'
	  /srv/easyproject/public_html/plugins/easyproject/init.rb:371:in `block in load_all_plugins'
	  /srv/easyproject/public_html/plugins/easyproject/init.rb:370:in `each'
	  /srv/easyproject/public_html/plugins/easyproject/init.rb:370:in `load_all_plugins'
	  /srv/easyproject/public_html/plugins/easyproject/init.rb:339:in `init!'
	  /srv/easyproject/public_html/plugins/easyproject/init.rb:391:in `<top (required)>'
	  /usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	  /usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
	  /usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	  /usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	  /srv/easyproject/public_html/config/initializers/22-change_plugins_order.rb:15:in `load'
	  /srv/easyproject/public_html/config/initializers/30-redmine.rb:21:in `<top (required)>'
	  /usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
	  /usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
	  /usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	  /usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
	  /usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.2.7.1/lib/rails/engine.rb:652:in `block in load_config_initializer'
	  /usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
	  /usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.2.7.1/lib/rails/engine.rb:651:in `load_config_initializer'
	  /usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.2.7.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
	  /usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `each'
	  /usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `block in <class:Engine>'
	  /usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
	  /usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
	  /usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
	  /usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	  /usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	  /usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	  /usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	  /usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	  /usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
	  /usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
	  /usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:415:in `call'
	  /usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
	  /usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	  /usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `each'
	  /usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `call'
	  /usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	  /usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	  /usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	  /usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
	  /usr/local/rvm/gems/ruby-2.3.3/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
	  /srv/easyproject/public_html/config/environment.rb:14:in `<top (required)>'
	  config.ru:3:in `require'
	  config.ru:3:in `block in <main>'
	  /usr/local/rvm/gems/ruby-2.3.3/gems/rack-1.6.5/lib/rack/builder.rb:55:in `instance_eval'
	  /usr/local/rvm/gems/ruby-2.3.3/gems/rack-1.6.5/lib/rack/builder.rb:55:in `initialize'
	  config.ru:1:in `new'
	  config.ru:1:in `<main>'
	  /usr/local/rvm/gems/ruby-2.3.3/gems/passenger-5.1.2/src/helper-scripts/rack-preloader.rb:110:in `eval'
	  /usr/local/rvm/gems/ruby-2.3.3/gems/passenger-5.1.2/src/helper-scripts/rack-preloader.rb:110:in `preload_app'
	  /usr/local/rvm/gems/ruby-2.3.3/gems/passenger-5.1.2/src/helper-scripts/rack-preloader.rb:156:in `<module:App>'
	  /usr/local/rvm/gems/ruby-2.3.3/gems/passenger-5.1.2/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
	  /usr/local/rvm/gems/ruby-2.3.3/gems/passenger-5.1.2/src/helper-scripts/rack-preloader.rb:29:in `<main>'

</details>

**Comment by mikitex70** [comment]
I've tried with Redmine 3.3.3 and Ruby 2.3.0 in a Docker container, but I cannot reproduce your error.
It seems to be similar to #13: both issues has been happened with Ruby 2.3, and both seems to happen in a easyredmine installation.
Can you give me the version of Rails in use?
Also maybe I'm missing some rule in file naming/positioning (I'm a Java programmer) but other plugins with similar file naming (like advanced_roadmap_v2) seems to work fine.
Give me some more time to investigate.

**Comment by amenk** [comment]
This is the feedback I got from EasyRedmine:

> Hello,
> 
> you will need to make sure that file init.rb only contains plugin registration and no gem requirements. You will also have to add a condition for Easy Redmine and an after init file (in case the plugin does have some gem requirements). First be sure that you have a backup.
> 
> We have manual on following link https://www.easyredmine.com/resources/redmine-enhancements-by-easy/other-redmine-plugins.
> 
> If you go through these tips I believe you will be able to make it functional.

can you try this? I will be happy to test...

**Comment by mikitex70** [comment]
Hi amenk, thanks for the documentation.
I've refactored the code based on those guidelines; you can find a quick and dirty version of the plugin in the `feature/easyredmineCompat` branch. With Redmine 3.3.2 works as before, I hope solves the problems with EasyRedmine.
If your test were successfully I will do some cleanup on the code and than I will do new release.

**Comment by amenk** [comment]
Redmine starts now when installing that branch.
If I put

     {{drawio_attach(test.png)}} or {{drawio_attach(test.svg)}}

into a wiki page

It displays 

     Error executing the drawio_attach macro (undefined method `svg?' for #<#<Class:0x00000003b03bc0>:0x007ff519d8a020>)

on rendering.

**Comment by amenk** [comment]
drawio(test.xml)

is working ... but I am more interested in the attach function to directly edit diagrams from within redmine

**Comment by mikitex70** [comment]
Try now, I've completed the refactor of the code: now is more clean and all macros will work fine (at least I home).

**Comment by amenk** [comment]
Awesome ...
iframe.drawIoEditor     margin-top: 50px; would fix the issue with overlapping top-bar
![screenshot_auswahl_030](https://cloud.githubusercontent.com/assets/1087128/25719778/e6c985fa-310a-11e7-9881-3112f0a662ac.png)

**Comment by mikitex70** [comment]
Glad to see that now is working.
For the iframe, I need a way to detect if the plugin is running in easyredmine or not, to be able to add the margin only if necessary.
Can you find an element in the page (a tag or a class, maybe the top bar) that can be recognized as specific for easyredmine? If so I can add the margin dynamically to accomodate different themes.

**Comment by amenk** [comment]
<body class="project-example-com controller-wiki action-show desktop-device non-easy-redmine-theme">

so it seems to be non-easy-redmine-theme - will this is a bit strange naming, but it should work

**Comment by amenk** [comment]
Can you include this CSS? (there is also a sidebar on the righ)

	.non-easy-redmine-theme iframe.drawioEditor {
	    top: 50px;
	    right: 40px;
	    width: calc( 100% - 40px );
	    height: calc( 100% - 50px );
	}

**Comment by mikitex70** [comment]
Is better if the drawio iframe stays over all elements of the page, the EasyRedmine menu too, to prevent leaving the editor without saving. Also this solution is theme independent.
So I've modified the z-index of the iframe to try to keep over the main menu. Give it a try from the `develop` branch, and if if not works then I will adopt your solution.

**Comment by amenk** [comment]
Jap it's pretty. Thank you!

**Comment by amenk** [comment]
fixed in *develop*
