### ISSUE TITLE
incorrect shapes redmine 3.3.0 current version of Draw.io

### ISSUE THREAD

**Issue by mrclicky** [mikitex70/redmine_drawio#2]
Just taking a template from draw.io flow chart section and adding it to a wiki page results in shapes being defaulted to rectangles and some with clear backgrounds getting filled in.

**Comment by mikitex70** [comment]
Let me try in the weekend.
But the plug-in does nothing more than including the scripts from draw.io: the shapes are drawn by those scripts so maybe there is some conflict with other scripts. Can you tell me what plugins you use?
Have you tried other browsers to see if it is a general problem or related to a specific browser?

**Comment by mrclicky** [comment]
I have Chrome 53.0.2785.116 m (64-bit), IE 11, Firefox 48.0.2
IE11 doesn't show the diagram at all.
Chrome seems to have changed all shapes to rectangle.
Firefox shows the same as chrome.

Current plugins are this one v0.1.2 and mylyn connector 2.8.2.stable

**Comment by mikitex70** [comment]
I think I've fixed the problem, but I'm unable to start my Redmine 3.3 (troubles with Docker) so it's tested only on Redmine 2.3.
Can you checkout from the develop branch and give a try? If it works I would release it in the master branch.

**Comment by mrclicky** [comment]
Sure thing. I'll do this morning and let you know. I should just be able to load it, restart the webserver and view the entry with the diagram correct?

**Comment by mrclicky** [comment]
Failed to initialize plugin:
<pre>
[ 2016-10-10 09:14:57.9694 11206/7f71cc069700 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /var/www/redmine-3.3.0: An error occurred while starting up the preloader.
  Error ID: 6b7510c7
  Error details saved to: /tmp/passenger-error-AYhbeU.html
  Message from application: /var/www/redmine-3.3.0/plugins/redmine_drawio/lib/hooks/view_hooks.rb:12: syntax error, unexpected end-of-input, expecting keyword_end (SyntaxError)
  /usr/local/share/gems/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
  /usr/local/share/gems/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
  /usr/local/share/gems/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
  /usr/local/share/gems/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
  /usr/local/share/gems/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:360:in `require_or_load'
  /usr/local/share/gems/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:317:in `depend_on'
  /usr/local/share/gems/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:233:in `require_dependency'
  /var/www/redmine-3.3.0/plugins/redmine_drawio/init.rb:4:in `<top (required)>'
  /usr/local/share/gems/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
  /usr/local/share/gems/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
  /usr/local/share/gems/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
  /usr/local/share/gems/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
  /var/www/redmine-3.3.0/lib/redmine/plugin.rb:155:in `block in load'
  /var/www/redmine-3.3.0/lib/redmine/plugin.rb:146:in `each'
  /var/www/redmine-3.3.0/lib/redmine/plugin.rb:146:in `load'
  /var/www/redmine-3.3.0/config/initializers/30-redmine.rb:21:in `<top (required)>'
  /usr/local/share/gems/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
  /usr/local/share/gems/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
  /usr/local/share/gems/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
  /usr/local/share/gems/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
  /usr/local/share/gems/gems/railties-4.2.6/lib/rails/engine.rb:652:in `block in load_config_initializer'
  /usr/local/share/gems/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
  /usr/local/share/gems/gems/railties-4.2.6/lib/rails/engine.rb:651:in `load_config_initializer'
  /usr/local/share/gems/gems/railties-4.2.6/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
  /usr/local/share/gems/gems/railties-4.2.6/lib/rails/engine.rb:615:in `each'
  /usr/local/share/gems/gems/railties-4.2.6/lib/rails/engine.rb:615:in `block in <class:Engine>'
  /usr/local/share/gems/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `instance_exec'
  /usr/local/share/gems/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
  /usr/local/share/gems/gems/railties-4.2.6/lib/rails/initializable.rb:55:in `block in run_initializers'
  /usr/share/ruby/tsort.rb:150:in `block in tsort_each'
  /usr/share/ruby/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
  /usr/share/ruby/tsort.rb:210:in `block (2 levels) in each_strongly_connected_component_from'
  /usr/share/ruby/tsort.rb:219:in `each_strongly_connected_component_from'
  /usr/share/ruby/tsort.rb:209:in `block in each_strongly_connected_component_from'
  /usr/local/share/gems/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `each'
  /usr/local/share/gems/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `tsort_each_child'
  /usr/share/ruby/tsort.rb:203:in `each_strongly_connected_component_from'
  /usr/share/ruby/tsort.rb:182:in `block in each_strongly_connected_component'
  /usr/share/ruby/tsort.rb:180:in `each'
  /usr/share/ruby/tsort.rb:180:in `each_strongly_connected_component'
  /usr/share/ruby/tsort.rb:148:in `tsort_each'
  /usr/local/share/gems/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers'
  /usr/local/share/gems/gems/railties-4.2.6/lib/rails/application.rb:352:in `initialize!'
  /var/www/redmine-3.3.0/config/environment.rb:14:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /usr/share/gems/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
  /usr/share/gems/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `eval'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'


[ 2016-10-10 09:14:57.9896 11206/7f71ecab1700 age/Cor/Con/CheckoutSession.cpp:285 ]: [Client 2-1] Cannot checkout session because a spawning error occurred. The identifier of the error is 6b7510c7. Please see earlier logs for details about the error.
</pre>

**Comment by mikitex70** [comment]
Fixed. My stupid mistake, indentation was gone and I missed an `end` to close the `module`.
Try again: do a `git pull`, restart the web server and the diagrams now should be fine.

**Comment by mrclicky** [comment]
ok. I have switched back to develop branch and pulled the changes. HEAD is now "462508e fix: usr: fixed missing end of module"

restarted the webserver and it doesn't seem to have an issue but the diagram looks the same. I tried to remove the {{drawio(diagram.xml)}} comment from my issue, save, and re-add it but again no change. is there a cache somewhere that I should clear?

**Comment by mikitex70** [comment]
No cache by server, but maybe the cache in the browser...
I've tested the plugin with Redmine 3.3.0 stable and it's working fine.
I have create a new flowchart diagram in www.draw.io, saved locally (File - Save as .. -> choose Device -> download diagram and saved as `flowchart.xml`), then in Redmine I've created a new Wiki page, attached the diagram and inserted the macro as `{{drawio(flowchart.xml)}}`, saved the page and diagram is showing.
The plugin instruct the browser to include a Javascript from www.draw.io with protocol HTTPS: can you check with the browser console if the file is downloaded or if there is some Javascript error?
Can you attach a screenshot of what is rendered in your browser?

**Comment by mrclicky** [comment]
I followed your steps as given. Here is my screenshot and flowchart.xml. 
Just to make sure, I restarted my apache instance again.

![lightbox](https://cloud.githubusercontent.com/assets/22597973/19279959/9c97b48e-8fb1-11e6-808a-a58db3884abf.png)

[flowchart.xml.txt](https://github.com/mikitex70/redmine_drawio/files/522438/flowchart.xml.txt)

**Comment by mikitex70** [comment]
Ok, now I've understood. I was looking the graph, not the shapes...
I've found the problem, I think tomorrow I will commit the fix.
Thanks for your support.

**Comment by mikitex70** [comment]
Problem fixed.
Do a pull from the develop branch, restart the web server and now the diagrams should look fine.

**Comment by mrclicky** [comment]
Looks good! Thanks a million.
