### ISSUE TITLE
Error 422 Unprocessable Entity

### ISSUE THREAD

**Issue by MathieuDuc35** [mikitex70/redmine_drawio#22]
Hi,

I have installed redmine and a lot of plugins to test it but I have a problem that I havent succeed to fix it's with redmine_drowio. The installation worked perfect and I try to use it and that works well but when I try to save it I have to connect again to redmine (that work) and after this I have a litle window who show a 422 error. I don't know from where that come. If you have any ideas ?
The problem com when I use the drawio_attached button (the DMSF don't work at all) and if I joined a local save diagram that show it fine with {{drawio(MyDiagram.xml, options)}}

This is my environment : 

> Environment:
  Redmine version                3.3.3.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            2.1.4
  Filesystem                     
Redmine plugins:
  a_common_libs                  2.3.0
  extra_queries                  2.2.7
  issue_charts                   1.3.0
  issuestats                     0.0.2
  parent_issue_filter            1.0.2
  redmine_ckeditor               1.1.4
  redmine_drawio                 0.6.0
  redmine_editor_preview_tab     0.1.5
  redmine_emojibutton            0.4.1
  redmine_favorite_projects      2.0.3
  redmine_import_issues          1.0.0
  redmine_issue_tabs             1.2.2
  redmine_issue_templates        0.1.5
  redmine_lightbox2              0.3.2
  redmine_questions              0.0.7
  redmine_stats                  0.0.1
  redmine_theme_changer          0.2.0
  redmine_wiki_html_util         0.0.1
  redmine_wiki_lists             0.0.7
  redmine_work_time              0.3.4
  sidebar_hide                   0.0.8

**Comment by mikitex70** [comment]
For the error about the DMSF button please read the README.md: the `drawio_attach` macro works only if you install the `redmine_drawio` plugin, which seems missing from your list. I'm working on disabling that button if the plugin isn't installed, but in the meanwhile don't use it if you don't install the `redmine_dmsf` plugin.

For the `drawio_attach` macro, I haven't understood your use case: the diagram comes from the usage of the `drawio` attachment? If so, again, read the README.md: the `drawio` macro works with `xml` diagram format, the `drawio_attach` and `drawio_dmsf` macros works with `png` and `svg` diagram format. You cannot use an xml diagram with the `drawio_attach` macro, you need to open it with the editor at www.draw.io and export it as `png` or `svg` with embedded xml.

Can you send me (as a post attachment) an example of diagram you use (just a portion)? I need to inspect it and to understand where is the problem because I'm unable to reproduce the HTTP 422 error.

**Comment by MathieuDuc35** [comment]
I have the redmine_drawio in my list ... when i save the diagram in .xml and put it as a file in redmine that show it well.
My problem is when I use the drawio attached button, i click it that add the lines in the wiki or in a issue. I have the image "double click to start drawing" so I double click on it, imake my diagram and then when I click on the "save" button redmine demand to reconnect to redmine (that work) and just after that I have the 422 error that unsaved my diagram ...
For the drawio_dmsf when I use it I have this in my wiki/issue  : "Error executing the drawio_dmsf macro (uninitialized constant DmsfFile)"

**Comment by MathieuDuc35** [comment]
This my redmine log when I try to save the diagram : 

Started  GET "/issues/3369.json" for 10.38.8.187 at 2017-05-15 09:24:44 +0200
Processing by IssuesController#show as JSON
  Parameters: {"id"=>"3369"}
  Current user: mduc (id=102)
  Rendered issues/show.api.rsb (8.4ms)
Completed 200 OK in 40ms (Views: 8.6ms | ActiveRecord: 3.7ms)
Started PUT "/issues/3369.json" for 10.38.8.187 at 2017-05-15 09:24:44 +0200
Processing by IssuesController#update as JSON
  Parameters: {"attachments"=>{"0"=>{"token"=>"dab846baf24fa7dfaff112d1a360b783a12efcac", "filename"=>"Untitled Diagram_1.png", "content-type"=>"image/png"}}, "issue"=>{"description"=>"\<p>{{drawio_attach(diagram.png, size=300)}}\</p>\r\n"}, "id"=>"3369"}
  Current user: mduc (id=102)
  Rendered common/error_messages.api.rsb (0.2ms)
Completed 422 Unprocessable Entity in 38ms (Views: 0.8ms | ActiveRecord: 2.8ms)

**Comment by MathieuDuc35** [comment]
No more answer ?

**Comment by mikitex70** [comment]
Sorry for the long delay but it was a bit difficult to reproduce the problem.
I've just found a possible source of the error: the maximum attachment size.
In the Redmine API specification explicitly says that if the attachment size is over the maximum allowed than it is not saved and an HTTP 422 error will be returned.
Try to increase the maximum allowed diagram size in the `file` tab of Redmine Settings, or try to save a more simple diagram, just to test if it works.
If this is the problem I would add some code to give a more clear error message (now is reported what the server says).

**Comment by MathieuDuc35** [comment]
It's not a problem of size .. I try to change in the settings but that doesn't change anythings. It's more like a permission problem or a missing attribute problem when it try to put the diagram in the issue

**Comment by mikitex70** [comment]
Try to use the plugin from the `develop` branch, it should write a more explicative message coming directly from Redmine. Maybe it gives some advice of what is going wrong.
