### ISSUE TITLE
Compatibility issue with Omniauth Google plugin

### ISSUE THREAD

**Issue by mvange** [mikitex70/redmine_drawio#23]
When attempting to add a diagram upon saving (from draw.io) the user is asked for a username/password however, since login was provided by Omniauth initially user does not have that information so currently impossible to use.

**Comment by mikitex70** [comment]
What plugin are you using?
I've search with Google and I've found various implementations of this kind of plugin.

**Comment by mvange** [comment]
I'm using https://github.com/twinslash/redmine_omniauth_google

Do you know of any others that the plugin works with correctly?

Thanks!

**Comment by mvange** [comment]
I should add that we are using a private cert (so it's reported as insecure by browsers) though the user has obviously accepted it by the time we get here so that *SHOULD* not be an issue.  

In truth, though, I don't know if that's contributing to the issue or not.
