### ISSUE TITLE
SVG Format: Error: Not a diagram file when double clicking on or near a text in the diagram [develop]

### ISSUE THREAD

**Issue by amenk** [mikitex70/redmine_drawio#25]
1. Edit issue or wiki page
2. Insert {{drawio_attach(foobar.svg)}}
3. Save
4. Double click to start drawing
5. draw a circle with a text in it
6. Save diagram
7. Double click the rendered diagram
8. The text is highlighted and draw.io loads
9. Popup Error: "Not a diagram file" from draw.io
10. Empty drawing space
11. Saving deleted the diagram
12. If I doubleclick out of the circle, not on the text, it works

**Comment by amenk** [comment]
Not 100% reproducible .. but seems to depend on where I click

**Comment by amenk** [comment]
Any idea?

**Comment by mikitex70** [comment]
Try the new version from the `develop` branch, I've fixed the closing tag of the SVG.

**Comment by amenk** [comment]
still happens sometimes ...

**Comment by mikitex70** [comment]
Hi amenk, try new new version from develop, it fixes this and other bugs.

**Comment by amenk** [comment]
jep, clicked lots of times, does not seem to happen any more. thank you!
