### ISSUE TITLE
When editing a diagram in a private note, it is posted public (develop, easyredmine)

### ISSUE THREAD

**Issue by amenk** [mikitex70/redmine_drawio#28]

**Comment by amenk** [comment]
Not related to private notes, but if I edit a diagram in a note, it posts a new note over and over again. Maybe this is intended?
![selection_292](https://cloud.githubusercontent.com/assets/1087128/26778124/42d04fb2-49e0-11e7-9713-bf83da269e23.png)

**Comment by amenk** [comment]
actually this is lower priority than #27 - I think most of the time it makes more sense to have diagram in the ticket head

**Comment by mikitex70** [comment]
Yes, it is done intentionally.
The notes cannot be update (at least with the current REST APIs), the only thing that can be done is adding a new note. Maybe it will change in the future, if I can find the correct API.

**Comment by amenk** [comment]
On easyredmine the note needs no updating cause the file name does not
change. Can we remove that adding-a-note for easyredmine?

**Comment by mikitex70** [comment]
Yes, you are right... with EasyRedmine there is no problem :smile:.
I will fix it now.
