### ISSUE TITLE
future feature: create and draw on an redmine wiki as sort of an embedded object

### ISSUE THREAD

**Issue by oparidae** [mikitex70/redmine_drawio#3]

**Comment by mikitex70** [comment]
Hi oparidae, I've released in the develop branch a new version of the plugin.
With this version there are two new macros, `drawio_attach` and `drawio_dmsf`.
The first expects diagrams as attachments, the other as a DMSF document.
Can you give a try to the `drawio_attach` macro? It uses a sort of embedded editing, see the README.md for details.
If you can, try also with different user privileges to see if the diagrams are editable only by users allowed to edit issues/wiki pages.

**Comment by oparidae** [comment]
simple test on redmine:
Environment:
  Redmine version                3.3.0.stable.15809
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2

the drawio_attach worked perfectly! Congrats!

It pop uped a permission for username and password (the .htpasswd style)

As soon as I have time I'll test the issues/wiki permissions

**Comment by oparidae** [comment]
I will test it tomorrow ! Huge thanks 

Enviado do meu iPhone

No dia 23/10/2016, às 19:13, Michele Tessaro <notifications@github.com> escreveu:

**Comment by mikitex70** [comment]
Closing this feature request as the plugin now handles embedded editing.
Thanks for your suggestion.
