### ISSUE TITLE
v0.7.1 is not working

### ISSUE THREAD

**Issue by dinya** [mikitex70/redmine_drawio#33]
After updating to redmine_drawio v0.7.1 it's not possible to insert diagrams to text:
niether
```
{{drawio_dmsf(fig)}}
```
or
```
{{drawio_attach(fig)}}
```
is not working. The figure "Double click to start drawing"
![](https://github.com/mikitex70/redmine_drawio/blob/master/spec/defaultImage.png?raw=true)
is shown. But double click hides this figure and it doesn't start draw.io window. 

Define diagram macros windows doesn't work too: "Insert diagram" button is not responsible to any clicks

![macros_window](https://user-images.githubusercontent.com/2182222/27586653-a699e3d8-5b5a-11e7-84b0-3acaf09dbecb.png)

Redmine installation
```
Environment:
  Redmine version                3.3.1.stable
  Ruby version                   2.2.3-p173 (2015-08-18) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  a_common_libs                  2.3.0
  computed_custom_field          1.0.5
  custom_menu                    1.7.4
  easy_wbs                       2016-0.0
  redmine_agile                  1.4.1
  redmine_checklists             3.1.5
  redmine_default_custom_query   1.2.0
  redmine_dmsf                   1.5.9
  redmine_drawio                 0.7.1
  redmine_issue_tabs             1.2.2
  redmine_latex_mathjax_macro    0.3.0
  redmine_lightbox2              0.3.2
  redmine_mentions               0.0.1
  redmine_my_page                0.1.10
  redmine_presentation           0.2
  redmine_pygments               0.0.1
  redmine_sublime_markdown_codemirror 0.0.1
  redmine_tags                   3.1.1
  redmine_wiki_extensions        0.7.0
  redmine_wiki_lists             0.0.7
  sidebar_hide                   0.0.8
  view_customize                 1.1.4
  wiki_graphviz_plugin           0.7.0
  wiki_issue_fields              0.5.2
```

**Comment by mikitex70** [comment]
If the editor does not start maybe there is a Javascript error: what browser are you using?
I've tested only with Firefox 52.2; it should work fine with Firefox from version 40 (I think) and with Chrome.
I'm using Linux so I cannot test with Internet Explorer, which is the major source of incompatibilities.
Try to open the browser console (there is something usefull also from Internet Explorer 9) and check if there are Javascript errors.

**Comment by dinya** [comment]
I use Chrome 59.0.3071.115 (64 bit) on Windows 7 (64 bit)

I add to wiki page ``Test_drawio`` for tests:
```
{{drawio_dmsf(diagrams/test3)}}
```

Browser console log state

* On page refresh

	```
	Test_drawio:116 GET http://SERVER/plugin_assets/redmine_drawio/javascripts/lang/drawio_jstoolbar-ru.js 
	drawio_jstoolbar-en.js:2 Uncaught TypeError: Cannot set property 'drawio_updating_page' of undefined
	    at drawio_jstoolbar-en.js:2
	(anonymous) @ drawio_jstoolbar-en.js:2
	Test_drawio:116 GET http://SERVER/plugin_assets/redmine_drawio/javascripts/lang/drawio_jstoolbar-ru.js 
	drawio_jstoolbar.js:91 Uncaught TypeError: Cannot read property 'drawio_btn_ok' of undefined
	    at HTMLDocument.<anonymous> (drawio_jstoolbar.js:91)
	    at j (jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js:2)
	    at Object.fireWith [as resolveWith] (jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js:2)
	    at Function.ready (jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js:2)
	    at HTMLDocument.J (jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js:2)
	```

* On click on "Double click to start drawing":

    ```
    drawioEditor.js:64 Uncaught ReferenceError: DRAWIO_URL is not defined
        at Object.showLoader (drawioEditor.js:64)
        at editDiagram (drawioEditor.js:77)
        at HTMLImageElement.ondblclick (Test_drawio:285)
    ```

But the plugin works well under Yandex browser 17.6.1.749 on Windows 7 (64 bit).

**Comment by mikitex70** [comment]
It seems the javascripts are old; try this:
* stop redmine
* remove the directory ``${REDMINE_HOME}/public/plugin_assets/redmine_drawio``
* start redmine

This will clean the published assets and force Redmine to re-read from the plugin sources.
Before this try a ``git pull`` on the ``redmine_drawio`` plugin directory, just to be sure to download the very last changes and pay attention if the pull operation works fine (maybe there are modified files that blocks the pull).
Or try to switch to the ``develop`` branch, which has the very latest sources (I think to release them the next weekend).

**Comment by dinya** [comment]
@mikitex70 

It's ok now:

1. I removed from ``plugins_asserts``
2. I use develop branch.

But
> Upd But in Yandex browser in editor there are no buttons for insert macroses.

The buttons are lost in Chrome browser now too.

**Comment by dinya** [comment]
Is not actual. Closed.
