### ISSUE TITLE
Cyrillic symbols are not saved from the embedded editor

### ISSUE THREAD

**Issue by bulbuliator** [mikitex70/redmine_drawio#36]
redmine_drawio plugin version 0.7.1 has a problem with cyrillic symbols 
when the diagram is created by drawio_attach macro from  the embedded editor.
When you try to save cyrillic symbols in embedded editor the following exception is thrown:
```
Uncaught Error: this string seems to contain (still encoded) multibytes
    at Object.arrayBufferToString (drawioEditor.js:386)
    at Object.extractImageData (drawioEditor.js:52)
    at receive (drawioEditor.js:115)
```
But embedding presaved diagram from draw.io with cyrillic symbols by obsolete drawio macro works fine:

![2017-07-07 14 37 22](https://user-images.githubusercontent.com/12321938/27956305-e25bb698-6321-11e7-93f7-ea979499dd13.png)

![2017-07-07 14 40 05](https://user-images.githubusercontent.com/12321938/27956367-35dd1e1a-6322-11e7-8056-5e7ad94f04aa.png)

**Comment by mikitex70** [comment]
Related to #35.
I will work on it this weekend.

**Comment by mikitex70** [comment]
No feedbacks in the last months.
Closing bug as seems to be fixed.
