### ISSUE TITLE
3.4.0 support

### ISSUE THREAD

**Issue by ausghostdog** [mikitex70/redmine_drawio#39]
Hi,
Was in the process of upgrading a test server to the latest Redmine version, during the upgrade process the following error occurred 
“Redmine::PluginRequirementError: redmine_drawio plugin requires a Redmine version between 2.6 and 3.3 but current is 3.4.0.stable.14186”

Like to know when 3.4 will be supported

**Comment by mikitex70** [comment]
Redmine 3.4.0 stable is already supported in the develop branch.
I hope to be able to release an official version this weekend.

**Comment by mikitex70** [comment]
Fixed by the release v0.8.0.
