### ISSUE TITLE
Display diagram from DMSF plugin

### ISSUE THREAD

**Issue by zolnierczyk** [mikitex70/redmine_drawio#4]
Hi mikitex70,

We are using DMSF plugin for managing documentation and works great. We ave also diagrams saved as documents and this will be great feature if wiki page can just simple display it. I am redmine administrator and javascript developer but I have no experience in Ruby but I would like to collaborate with development. If you don't mind I would like prepare patch which add such functionality to this plugin?

**Comment by mikitex70** [comment]
I'm working on feature request #3 (with some nice result) and now I'm studing where to save diagrams.
I've successfully saved diagrams in DMSF (with versioning :-) ) but I need to save also as attachment for those don't using DMSF.
I can work on it only on the weekends, but I hope to have something working for the next weekend.
Thanks for your offer, I will need your support for testing and suggestions.
Stay tuned :-)

**Comment by oparidae** [comment]
Tks mikitex!

**Comment by mikitex70** [comment]
Hi zolnierczyk, I've released in the develop branch a new version of the plugin.
With this version there are two new macros, `drawio_attach` and `drawio_dmsf`.
The first expects diagrams as attachments, the other as a DMSF document.
Can you give a try to the `drawio_dmsf` macro? It also uses a sort of embedded editing, see the README.md for details.
If you can, try also with different user privileges to see if the diagrams are editable only by users allowed to edit issues/wiki pages and to manipulate documents in DMSF..

**Comment by mikitex70** [comment]
Closing this feature request as the plugin now can handle DMSF documents.
