### ISSUE TITLE
Avoid Duplicate Diagram for Easyredmine

### ISSUE THREAD

**Issue by amenk** [mikitex70/redmine_drawio#40]
Same as #30, but in easy redmine it is possible to solve.
Can you fix this :-) ?

**Comment by mikitex70** [comment]
Where it happens?
I've tested in wiki pages with the ``drawio_attach`` macro and the diagrams are saved without versioning, as expected.
To detect EasyRedmine I check if there is a plugin registered as ``:easy_redmine``; is changed something?

**Comment by amenk** [comment]
In issues, the note is duplicated. The versioning works well, but the issue note is duplicated.
