### ISSUE TITLE
saving draw.io diagram -> "Attachment extension  is not allowed"

### ISSUE THREAD

**Issue by quimicefa** [mikitex70/redmine_drawio#54]
Hello,
I'm facing an issue when saving DrawIO diagram in a redmine issue. Not sure if this is caused by incorrect redmine configuration (extension allowed).

Steps to reproduce:
Go to a random issue
Edit
Insert drawio diagram,
![image](https://user-images.githubusercontent.com/5465238/37602208-2f576630-2b8c-11e8-91fa-27456135c1f3.png)
double-click to edit diagram
![image](https://user-images.githubusercontent.com/5465238/37602284-50f76e0c-2b8c-11e8-810b-2fdaefabce94.png)
saving the diagram "extension not allowed"
![image](https://user-images.githubusercontent.com/5465238/37602745-54b4908c-2b8d-11e8-94fc-0a45706732d3.png)

--> The diagram is not saved in the issue. 

Getting HTTP 422 error:
[ 2018-03-19 13:53:42.4981 129550/7f1b369cf700 age/Cor/Con/ForwardResponse.cpp:206 ]: [Client 2-6] Processing 57 bytes of application data: "33\r\n{"errors":["Attachment extension  is not allowed"]}\r\n"

Maybe related to https://github.com/mikitex70/redmine_drawio/issues/48 (?)

Extensions allowed as per "Settings/Files/Allowed extensions":
doc, docx, pdf, xlsx, xls, txt, gif, tif, jpg, jpeg, png, ppt, mp3, wav, avi, mpg, mpeg, wmv, gz, gzip, rar, tgz, zip, html, swf, exe, vsd ,mp4, xml, msg, mov, oft, pptx, mdb, sql, ics, xml, svg, png

Environment:
  Redmine version                3.4.4.stable
  Ruby version                   2.3.4-p301 (2017-03-30) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            1.7.1
  Filesystem                     
Redmine plugins:
  advanced_roadmap_v2            2.4.2
  easy_baseline                  1.4
  easy_gantt                     1.10
  easy_gantt_pro                 1.10
  easy_wbs                       2016-0.0
  redmine_agile                  1.4.5
  redmine_checklists             3.1.5
  redmine_ckeditor               1.1.4
  redmine_contacts               4.1.1
  redmine_contacts_helpdesk      3.0.9
  redmine_dmsf                   1.6.0
  redmine_drawio                 0.8.1
  redmine_people                 1.3.0

Thx.

**Comment by mikitex70** [comment]
The problem was on the API call to save the attachment, the documentation is not so clear.
Try the develop branch, the bug should be fixed now.

**Comment by mikitex70** [comment]
I hope to release it the next weekend, I've been busy with the plantuml-markdown plugin.
