### ISSUE TITLE
MathJax library URL is disabled

### ISSUE THREAD

**Issue by dinya** [mikitex70/redmine_drawio#56]
MathJax library URL is shown in settings, but it's not editable.

![mathjax_lib_path](https://user-images.githubusercontent.com/2182222/39129170-3a8b9028-4723-11e8-9539-e3a251ea1c0a.png)

``redmine_drawio`` v0.8.1.

**Comment by mikitex70** [comment]
Fix released in version `v0.8.2`, closing issue.

**Comment by dinya** [comment]
@mikitex70 

Thanks a lot!
