### ISSUE TITLE
error save draw.io in wiki page (redmine:3.4.6)

### ISSUE THREAD

**Issue by Sergey-sirius** [mikitex70/redmine_drawio#59]
Rendered plugins/redmine_drawio/app/views/redmine_drawio/_macro_dialog.html.erb (0.4ms)
Completed 200 OK in 204ms (Views: 200.1ms | ActiveRecord: 1.4ms)
Started POST "/uploads.json?filename=aa1_1.png" for 176.116.193.101 at 2018-09-06 06:59:54 +0000
Processing by AttachmentsController#upload as JSON
  Parameters: {"filename"=>"aa1_1.png"}
  Current user: admin (id=1)
Saving attachment '/home/redmine/data/files/2018/09/180906065954_aa1_1.png' (14727 bytes)
  Rendered attachments/upload.api.rsb (0.7ms)
Completed 201 Created in 43ms (Views: 11.9ms | ActiveRecord: 5.2ms)
Started GET "/projects/sitepark/wiki/Wiki_sitepark.json?include=journals" for 176.116.193.101 at 2018-09-06 06:59:54 +0000
Processing by WikiController#show as JSON
  Parameters: {"include"=>"journals", "project_id"=>"sitepark", "id"=>"Wiki_sitepark"}
  Current user: admin (id=1)
  Rendered wiki/show.api.rsb (2.7ms)
Completed 200 OK in 33ms (Views: 11.6ms | ActiveRecord: 5.4ms)
Started PUT "/projects/sitepark/wiki/Wiki_sitepark.json" for 176.116.193.101 at 2018-09-06 06:59:54 +0000
Processing by WikiController#update as JSON
  Parameters: {"attachments"=>{"0"=>{"token"=>"17.e1e55768930d88b6a17418b1602cf3a29168c2275dd9fcf944b8987b23f27ec7", "filename"=>"aa1_1.png", "content-type"=>"image/png"}}, "wiki_page"=>{"text"=>"# Wiki sitepark\r\n\r\n{{drawio_attach(aa1_1.png,size=111)}}\r\n"}, "project_id"=>"sitepark", "id"=>"Wiki_sitepark"}
  Current user: admin (id=1)
Completed 500 Internal Server Error in 27ms (ActiveRecord: 6.9ms)

NoMethodError (undefined method `empty?' for nil:NilClass):
  plugins/redmine_messenger/lib/redmine_messenger/patches/wiki_page_patch.rb:38:in `send_messenger_update'
  app/models/wiki_page.rb:217:in `block in save_with_content'
  app/models/wiki_page.rb:216:in `save_with_content'
  app/controllers/wiki_controller.rb:176:in `update'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode

**Comment by mikitex70** [comment]
The problem seems to be related to te redmine_messenger plugin...
Are you using plain Redmine or some commercial distribution like EasyRedmine?
Can you give me the version of the `redmine_messenger` plugin and, possibly where I can download it?
I would like to try to setup a test environment to reproduce the error.

**Comment by mikitex70** [comment]
No more feedback, issue closed.
Feel free to reopen it if you think this is the case.
