### ISSUE TITLE
DMSF linking

### ISSUE THREAD

**Issue by jeshio** [mikitex70/redmine_drawio#6]
Hello!
I want to use plugin with dmsf, but I have a problem.

![image](https://cloud.githubusercontent.com/assets/1515657/19999841/645de53c-a296-11e6-830a-25d6f3a0b766.png)

On the screen you can see my diagram-file with extension .xml.
This file id is 2.

So, I link it:
![image](https://cloud.githubusercontent.com/assets/1515657/19999911/b9674c08-a296-11e6-9047-8b6989a3829d.png)

And result:
![image](https://cloud.githubusercontent.com/assets/1515657/19999945/e22804b6-a296-11e6-8c12-ca48f4e759ca.png)

Why is it?)

**Comment by mikitex70** [comment]
The image ``Double click to start drawing`` is a placeholder to start a new diagram, that when saved will create a new DMSF document named ``2.png`` (from your screenshots).
The macro ``drawio_dmsf`` works only by starting a new diagram as needs to save it as an PNG image with embedded XML source.
So in your case you need to specify something like ``Redmine/Redmine Roles Sequence`` as diagram name, which inserts the macro ``{{drawio_dmsf(Redmine/Redmine Roles Sequence)}}``.
From there you can then double click the placeholder to open the editor, and then import your existing diagram in XML format.
After saving it, a document ``Redmine/Redmine Roles Sequence.png`` will be created, with a new version every time you modify it. Every time you double click on the diagram image, the editor will start, letting you to modify the diagram.
If you need to extract the XML source, open the diagram editor and export as XML. I hope exporting in XML would be a rare case, as working with the PNG+XML format seems to be enough flexible.
Maybe the [README](../blob/master/README.md) is not so clear, I will try specify more explicitly this kind of interaction.

**Comment by jeshio** [comment]
Thank you for responding.
Ok, but now I have another problem with save.

After click button "Save" I got a login box:
![image](https://cloud.githubusercontent.com/assets/1515657/20028201/1ad982b0-a34d-11e6-8509-5c2d420586db.png)

I'm writing my redmine login/password and getting next:
![image](https://cloud.githubusercontent.com/assets/1515657/20028210/51f60868-a34d-11e6-9d54-4960abf13e2f.png)

**Comment by mikitex70** [comment]
The error was returned by the DMSF module when attempting to save the document in an non-existent folder.
Make sure the folder exists before attempting to save a diagram; if it is missing create it through the DMSF module.
Also, make sure to enable the WebDAV capabilities (with Read/Write support) in the DMSF plugin settings.

**Comment by jeshio** [comment]
Thanks, it works!)

**Comment by cdsousa** [comment]
Hi @mikitex70 , I also have the "Sign in" dialog problem although everything is OK with the folder (I guess).
Is there any other known situation where this can happen?

**Comment by mikitex70** [comment]
The `README` explains the settings needed by the plugin.
If you get a login dialog then you are not authorized to upload files using the WebDAV functionality of `DMSF`. Search in the `DMSF` documentation how to use the WebDAV directly (in Linux is quite easy, in Windows you need to install a client). Also check the `DMSF` plugin version, maybe there is a bug (the WebDAV has been completely rewritten in the last versions).
If you cannot resolve, give me the exact installed plugin versions so I can try to replicate your environment; you can use the `info` link in the Redmine administration page.

**Comment by cdsousa** [comment]
@mikitex70  Thanks, it is working now.
I updated DMFS, and the "Sign in" dialog appeared, but I could successfuly put my credentials and it never asked it again.
I had, however, to disable the option "Use project name for project folder" option in DMSF for it to works, or else I got an error about the folder not existing.

**Comment by mikitex70** [comment]
Yes, that option has troubles, I've filed a bug to the DMSF project.
They have fixed it, but I think isn't released jet.
