### ISSUE TITLE
Is there support for Redmine 4?

### ISSUE THREAD

**Issue by mrPsycho** [mikitex70/redmine_drawio#62]
hello!

does it work on redmine 4?

**Comment by mikitex70** [comment]
Never tested on Redmine 4.
It should work, I'm not using Rails deeply so I don't expect incompatibilities.

**Comment by goodnewz** [comment]
I am using it with Redmine 4.0.2 and it works fine. Hope this helps.

**Comment by mikitex70** [comment]
Thanks for yout contribute @goodnewz .

**Comment by mrPsycho** [comment]
yep! it works! thanks!
