### ISSUE TITLE
How to upgrade

### ISSUE THREAD

**Issue by yousefchtourou** [mikitex70/redmine_drawio#63]
How to upgrade from 0.8.2 to 0.8.3

**Comment by mikitex70** [comment]
Simply update the plugin sources (eg. `git pull`) and restart Redmine.

**Comment by yousefchtourou** [comment]
without delete the old folder ?

**Comment by yousefchtourou** [comment]
git pull not work

**Comment by mikitex70** [comment]
How do you have installed the plugin?
If you have download the first time with `git clone`, now a `git pull` will be enough. You can try a `git fetch`  before the `git pull` just to be sure to download last changes.
If you have downloaded it as a zip file, just delete the old plugin folder (best, move it out of the `plugins` folder`), download the new version and de-zip it.

**Comment by yousefchtourou** [comment]
i delete the zip

**Comment by mikitex70** [comment]
No more feedback, issue closed.
Feel free to reopen it if you think this is the case.
