### ISSUE TITLE
In wiki edit, don't add draw.io button to ckeditor

### ISSUE THREAD

**Issue by Heng1984617** [mikitex70/redmine_drawio#67]
I have installed redmine_drawio but it doesn't show in ckeditor of wiki editor.
why?

**Comment by mikitex70** [comment]
What version of Redmine? And what kind of distribution (Docker, Bitnami, EasyRedmine, standalone install)?
Have you selected in the main Redmine options `ckeditor` as default markup?
Give me some info otherwise I cannot help you...

**Comment by Heng1984617** [comment]
I have installed EasyRedmine. after then installed redmine_drawio plugins.
But I cannot see  drawio(diagram) button in ckeditor of wiki editor.

**Comment by Heng1984617** [comment]
I want to talk with you through skype. my skype is live:jamesp1984617

**Comment by mikitex70** [comment]
It's not easy for me to test with EasyRedmine, it's a commercial distribution.
I've tested the plugin with the [free ckeditor plugin](https://github.com/a-ono/redmine_ckeditor); the ckeditor in EasyRedmine should be detected in the same way.
Are you sure the plugin is correctly installed? Check in the `Plugins` link in the `Administration` page if the plugin is there: if it doesn't appear then something wrong is happened on startup.
And I don't handle roles to manage diagrams so... are you sure you are expecting to see my plugin?

**Comment by Heng1984617** [comment]
Hello. I installed redmine-drawio plugin in correct way. I see it  in Administraion page.
I think it is an error. Redmine drawoio plugin is not compatible with easyredmin ckeditor.
![image](https://user-images.githubusercontent.com/34353497/60851261-9ee36f00-a21c-11e9-98c6-03ac816ba2b0.png)
what I am trying to say is that you can fix the issue or not in easyredmine?

**Comment by mikitex70** [comment]
It was compatible, at least when [this comment](https://github.com/mikitex70/redmine_drawio/issues/21#issuecomment-304522102) was written.
Please note also that EasyReadmine has published a similar plugin after mine, and the role management you are expecting comes from their implementation.
As the plugin seems correctly installed, the only problem now seems to be the missing button from the ckeditor toolbar; the button is added through javascript so I expect there is an error logged in the browser. Try to open the web console with the CTRL-F12 hotkey and check if there are errors.
In the weekend I will try to revive the environment where I've simulated the EasyRedmine environment.

**Comment by Heng1984617** [comment]
When opening web console, I don't see any error.

**Comment by mikitex70** [comment]
Fix merged to branch master with tag v0.9.1.
Closing this issue as fix seems to solve the problem.
Thanks for reporting this issue.
