### ISSUE TITLE
Add draw.io button to redmine_wysiwyg_editor

### ISSUE THREAD

**Issue by kay54068** [mikitex70/redmine_drawio#69]
I have installed redmine_wysiwyg_editor ,how Add draw.io button to redmine_wysiwyg_editor toolbar ?

* redmine_wysiwyg_editor:
https://github.com/taqueci/redmine_wysiwyg_editor

**Comment by mikitex70** [comment]
I've tested it only with the [redmine_ckeditor plugin](https://github.com/a-ono/redmine_ckeditor).
Let me check in the weekend how works this other plugin, maybe there is some difference that I can fix.

**Comment by mikitex70** [comment]
With some difficulty but I've managed to add the editing buttons in the `redmine_wysiwyg_editor` toolbar.
Can you give it a try pulling from the `develop` branch.

**Comment by mikitex70** [comment]
Merged on the `master` branch.
Thanks for letting me discover the [redmine_wysiwyg_editor](https://github.com/taqueci/redmine_wysiwyg_editor) plugin.
No feedback so I'm assuming it's all fine.
Feel free to open other issues if you find bugs.
