### ISSUE TITLE
Error when saving diagram with version 0.9.1

### ISSUE THREAD

**Issue by nanego** [mikitex70/redmine_drawio#72]
Hello

We tried to update the plugin today, but we get an error when saving diagrams with the latest version of the plugin (v0.9.1) :

![copie_message](https://user-images.githubusercontent.com/1620522/72071718-bc3ce700-32ec-11ea-98b8-676bf24b4e29.png)

With the previous version, v0.9.0, everything works fine.

**Comment by mikitex70** [comment]
Thanks for reporting.
There was a small bug in the base64 decoding routine; now should be fixed in the develop branch.
Give it a try if you can, tomorrow  I will release the new official version.

**Comment by mikitex70** [comment]
Released version v0.9.2 of the plugin with this fix.
Thanks again for reporting it.

**Comment by nanego** [comment]
Thank you for taking care of it and being so quick.
