### ISSUE TITLE
Saving a diagram does not work: "Current user: anonymous" / "Forbidden 403"

### ISSUE THREAD

**Issue by ju-h4** [mikitex70/redmine_drawio#78]
Saving a diagram is not possible with my installation.

The logs indicate that the username is not set correctly when saving ("_anonymous_") and Redmine probably rejects the upload for this reason:
```
redmine_1     | Started POST "/uploads.json?filename=testing_5.drawio" for x.x.x.x at 2020-05-15 23:29:14 +0000
redmine_1     | Processing by AttachmentsController#upload as JSON
redmine_1     |   Parameters: {"filename"=>"testing_5.drawio"}
redmine_1     |   Current user: anonymous
redmine_1     | Filter chain halted as :authorize_global rendered or redirected
redmine_1     | Completed 403 Forbidden in 7ms (ActiveRecord: 2.6ms)
```

Any hints how to solve that?

**My configuration:**

Docker-image: bitnami/redmine:4
```
Environment:
  Redmine version                4.1.1.stable
  Ruby version                   2.6.6-p146 (2020-03-31) [x86_64-linux]
  Rails version                  5.2.4.2
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Git                            2.26.2
  Filesystem                     
Redmine plugins:
  plantuml                       0.5.1
  redmine_drawio                 0.9.5
  redmine_issue_dynamic_edit     0.7.2
```

**Comment by mikitex70** [comment]
It was not tested on Redmine 4.1, but I've successfully reproduced your issue.
I will fix it in the next days.

**Comment by mikitex70** [comment]
It isn't a bug, you must enable the REST API.
Go in `Administration` -> `Settings` -> `API` tab and check the `Enable REST web service` flag.

**Comment by ju-h4** [comment]
@mikitex70 Oh well, yes thanks! I totally forgot about this when I reinstalled redmine.

**Comment by tomcss** [comment]
I ran into this same problem. It might be worth including it in the documentation on draw_attach.

**Comment by mikitex70** [comment]
It was already mentioned in the `README.md`.
I've enhanced the paragraph to let it a bit more visible, adding also some more detail on the configuration.
