### ISSUE TITLE
Compatibility with Wiki Extensions: Don't duplicate content of Header and Footer pages

### ISSUE THREAD

**Issue by wwwindisch** [mikitex70/redmine_drawio#79]
## Current Behavior
We're using the draw.io plugin together with the Wiki Extensions Plugin in the same Redmine installation. Wiki Extensions ships many additional features for Redmine Wikis. One of them are Header and Footer pages, whose contend is prepended (respectively appended) to all pages in the Project Wiki. Typical content for the Header page is e.g. the table of content macro `{{toc}}`, which brings a TOC to all pages.

For some reason, the draw.io plugin copies the content from the Header and Footer page to the current wiki page every time the drawing is saved. It looks like that:

_Original Page:_
```
# My Wiki Page
{{drawio_attach(Overview_20.png,size=4000)}}
```

_After editing and saving the "Overview" draw.io image twice:_
```
<div id="wiki_extentions_header">

{{>toc}}

</div>


<div id="wiki_extentions_header">

{{>toc}}

</div>

# My Wiki Page
{{drawio_attach(Overview_22.png,size=4000)}}

{{fnlist}}

<div id="wiki_extentions_footer">

` `

</div>

{{fnlist}}

<div id="wiki_extentions_footer">

` `

</div>
```

Consequently, we end up with e.g. with many TOCs after editing the draw.io image multiple times.

## Expected Behavior
Don't copy any content from the Wiki Extensions special pages "Header" and "Footer" to the current page, when saving a draw.io image.

**Comment by mikitex70** [comment]
Hi @wwwindisch, can you specify versions of Redmine and the drawioand wiki extesions plugins?
I need to reproduce the problem to be able to fix it.

**Comment by wwwindisch** [comment]
Thanks for your quick reply and sorry for leaving this information out in my first post.
Environment:
  ```
Redmine version                4.0.5.stable
  Ruby version                   2.6.5-p114 (2019-10-01) [x86_64-linux]
  Rails version                  5.2.3
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.10.4
  Mercurial                      4.8.2
  Bazaar                         2.8.0
  Git                            2.20.1
  Filesystem                     
Redmine plugins:
  _query                         0.0.5
  external_links_in_new_window   0.9
  redmine_agile                  1.5.0
  redmine_checklists             3.1.16
  redmine_contacts               4.2.5
  redmine_drawio                 0.9.0
  redmine_issue_templates        0.3.6
  redmine_my_page_paginations    1.0.0
  redmine_wiki_extensions        0.9.0
  redmineup_tags                 2.0.8
  sidebar_hide                   0.0.8
```

Since it's a production environment, the plugins haven't been updated to the very last version, yet. But as far as I've screened the issue lists, there haven't been any fixes for the described problem meanwhile.
Thanks as lot in advance!

**Comment by mikitex70** [comment]
Hi @wwwindisch, I've pushed a fix in the `develop` branch.
Give it a try, if all works fine I will release it.

**Comment by wwwindisch** [comment]
Sorry for the late reply; it took a while to get a maintenance time slot for trying.
Good news: The fix seems to work! Thanks a lot for your quick response!
