### ISSUE TITLE
Resize drawio_dmsf?

### ISSUE THREAD

**Issue by jallakim** [mikitex70/redmine_drawio#8]
Hi,

Really great plugin!

Maybe a stupid question, but is there a way to resize images printed by the `drawio_dmsf` macro? (similar to the `zoom` option for the `drawio` macro).

**Comment by mikitex70** [comment]
They are simple PNG images so yes, it's possible.
Give me some time to implement it, it's not difficult but I work on it in my free time :-)

**Comment by jallakim** [comment]
Excellent! No worries about timeframe -- totally understand it.

**Comment by jallakim** [comment]
Ah, didn't notice this commit. I tested it, and it works fine. Thanks, @mikitex70!
