### ISSUE TITLE
Warning "app.diagrams.net will stop working for embed mode. Please use embed.diagrams.net"

### ISSUE THREAD

**Issue by wwwindisch** [mikitex70/redmine_drawio#80]
Dear @mikitex70,

For a couple of days the warning "app.diagrams.net will stop working for embed mode. Please use embed.diagrams.net" pops up in the draw.io editor. I assume that it's just a server URL setting, which needs to be changed such that it points to the new URL?

![Error Message draw.io](https://user-images.githubusercontent.com/28566230/94121999-4795e280-fe52-11ea-9628-c7ef72efc06d.png)

**Comment by mikitex70** [comment]
Thanks for reporting this change, I will fix it as soon as possible.
In the meanwhile you can override the default value changing the `Draw.io service URL` in the plugin settings page; you can set it to `https://embed.diagrams.net` and it should work.

**Comment by mikitex70** [comment]
Updated the default value.
Checkout the v0.9.7 version for the fix.
Thanks again for reporting this issue.

**Comment by wwwindisch** [comment]
Wow! That was quick! Thanks a lot for the fix.
