### ISSUE TITLE
Error When saving

### ISSUE THREAD

**Issue by SeminYun** [mikitex70/redmine_drawio#82]
When We save Draw.io, We can 
show error message

![image](https://user-images.githubusercontent.com/5058355/96351557-1332e080-10f7-11eb-9634-0d7043223eda.png)

When we edit descript, All draw.io is gone..

**Comment by SeminYun** [comment]
We are using Bitnami Redmine 4.1.x

**Comment by SeminYun** [comment]
Resolved

![image](https://user-images.githubusercontent.com/5058355/96351813-01523d00-10f9-11eb-91f3-ad50c9513525.png)

**Comment by mikitex70** [comment]
Closing issue, as it is resolved.
