### ISSUE TITLE
Request: Toggle layers

### ISSUE THREAD

**Issue by AThomsen** [mikitex70/redmine_drawio#86]
It would be nice if layers could be toggled the same way it is possible when draw.io drawings are exported as html.

**Comment by mikitex70** [comment]
Hi @AThomsen, in the `develop` branch there is a new preliminary version of the plugin.
It is somewhat a breaking change, in the sense that the `drawio` macro does nothing: the code is merged in the `drawio_attach` macro.
The `drawio_attach` and `drawio_dmsf` macros have now full support to diagrams in XML format; using the editor toolbar buttons is the easiest way to write/edit the macro code. In your case in the `layers` field set a list of comma separated number of layers (0 based) you wish to show initially; then a layer selector will appear when the mouse is over the diagram.
I need to do some more testing, but it seems to work fine.

**Comment by mikitex70** [comment]
Released in the `v1.0.0` version of the plugin.
Thanks for your enhancement suggestion.
