### ISSUE TITLE
Diagram could not be saved to DMSF

### ISSUE THREAD

**Issue by illetschko** [mikitex70/redmine_drawio#87]
I did a new installation of Redmine version 4.1.1.stable
on Debian 10, with 
redmine_drawio  v0.9.9
redmine_dmsf  v2.4.5

works amazing, !!
This is really a great thing!!!!

Until I come to save. Message: "Error saving diagram: Make sure the DMSF folder exists and is accessible"
But saving with WebDAV works (with VS Code "Remote Workspace" plugin).

In 'production.log' of redmine I found:
Completed in: 97 ms | 409 [https://redmine.mydomain.at/dmsf/webdav/4/test.png]
The '4' is probably because it was the 4th project I created.

If I change line  290 of 'macros.rb':
from: `"#{project.id}/#{diagramName}"`
to: `"#{project.identifier}/#{diagramName}"`
... it works excellent!

Do I have some mis-configuration or what is wrong?

**Comment by mikitex70** [comment]
Hi @illetschko,
I've done a quick check and yes, something is not working as expected.
The code was born with Redmine 3.0, so maybe something has changed (or I've made a mistake).
I will do some more investigation in the weekend.
Thanks for reporting.

**Comment by mikitex70** [comment]
Ive checked an old installation (Redmine 3.3.2 and DMSF 1.5.9) and works fine with and without your fix.
I suppose the code was from older code, maybe in the latest versions something has changed/dropped.
But your fix works fine in older versions too, so thanks for reporting.
It will be released in the next major, I hope in this weekend.

**Comment by mikitex70** [comment]
Fixed in the new `v1.0.0` release.
Thanks for reporting the issue.
