### ISSUE TITLE
Redmine 4.0.1

### ISSUE THREAD

**Issue by lcasanova78** [mikitex70/redmine_drawio#88]
I have used the plugin in redmine 3.3.0 and everything is correct, but when I install it in redmine 4.0.1 the icon to create the draw.io diagram does not appear.
It is not compatible with 4.0.1 or I have done something wrong. I have installed it the same as in 3.3.0 and I have activated the REST API.

**Comment by mikitex70** [comment]
It's tested with Redmine 4.1.1.
Just tested with Redmine 4.0.1, to be sure all is working fine: the icon for the `drawio_attach` in the editor is there and functions as expected, in textile and markdown mode.
Check in the browser console if there are Javascript errors; try also to clean the browser cache.
The 4.0.1 is a new installation or an already installed Redmine? What flavor of Redmine is (vanilla, EasyRedmine, Bitname, ecc.)? What other plugins are installed?
Without more info I cannot help you...

**Comment by mikitex70** [comment]
No more feedback, closing this issue.
