### ISSUE TITLE
Errors on drawio_attach and drawio_dmsf

### ISSUE THREAD

**Issue by Yopii** [mikitex70/redmine_drawio#9]
Hi,

The plugin is great and works correctly with the '**_drawio_**' macro.
However, I have an error if I use the '**_drawio_attach_**' and '**_drawio_dmsf_**' macros.

> Error executing the drawio_dmsf macro (undefined method `editable?' for #<Journal:0x007fdfd55bc0e0> Did you mean? editable_by?)

> Error executing the drawio_attach macro (undefined method `editable?' for #<Journal:0x007fdfd55bc0e0> Did you mean? editable_by?)

**Infos**: 
- Redmine version                    3.3.1.stable.15949
- Ruby version                          2.3.0-p0 (2015-12-25) [x86_64-linux]
- Rails version                           4.2.7.1
- progressive_projects_list        1.0.0
- redmine_agile                        1.4.2
- redmine_checklists                 3.1.5
- redmine_dmsf                        1.5.8
- redmine_drawio                     0.3.2
- redmine_editor_preview_tab  0.1.5

**Comment by mikitex70** [comment]
I'm using version 1.5.6 of DMSF, maybe something has changed.
Give me the weekend, I will fix it.

**Comment by Yopii** [comment]
OK ! Thank you !

**Comment by Yopii** [comment]
Hi, 

Thanks for the fix but now I have two other problems. 

- The first, for the 3 macros I get this message when importing "_drawio unsupported item_". 
- The second is that I do not have the icons with each time I change the content. Their appearance seems random.

Thank you for yout help.

**Comment by mikitex70** [comment]
As stated in the README, the only supported items are Issues and Wiki pages. What kind of items do you need to be able to handle diagrams? Maybe I will be able to support those items too.

What are the "icons" you are referring too? The icons/buttons in the editor toolbar are available only on Issues and Wiki pages, consistently to the documentation. There are times when the diagrams are not rendered?

**Comment by mikitex70** [comment]
No other feedbacks in the last months.
I suppose the problems are resolved so I'm closing this issue.
I'm almost ready to release a new version of the plugin: feel free to open a new issue if you still have problems with the latest version.
