### ISSUE TITLE
Error when referencing or creating Draw.IO Diagram with Diagram Format XML

### ISSUE THREAD

**Issue by gordwcampbell** [mikitex70/redmine_drawio#90]
Hi! Firstly, thanks for building such an awesome plugin!

We have found an issue when creating or referencing existing Draw.IO diagrams in Redmine when they are of the XML type.

To step through the problem:

1 - We edit a Wiki page and click the "Attach Draw.IO Diagram" button from the toolbar.
2 - Fill out as though we are making a XML diagram type
![image](https://user-images.githubusercontent.com/83330627/116354836-53a8af00-a83c-11eb-9a5c-9f45bcf347e9.png)
3 - Click Insert Macro
4 - Save the Wiki Page,
5 - We receive the error text "Failed to execute 'addEventListener' on 'EventTarget': parameter 2 is not of type 'Object'."

Both SVG and PNG versions work correctly.

Version / Build Info:
Redmine 4.1.1.stable
From Turnkey Linux
redmine_drawio 1.0.0

Hoping this is an easy fix!

Cheers,

G

**Comment by gordwcampbell** [comment]
Also - weirdly, the diagram displays correctly if you're not signed in.

**Comment by mikitex70** [comment]
Hi @gordwcampbell,
can you tel me what browser you are using? I've done my tests with Firefox, maybe I've used some Javascript not so compatible with other broowsers.

**Comment by gordwcampbell** [comment]
Hi,

I just went in an re-tested and everything seems to be working now. 

I was using Chrome when I was experiencing problems. 

Marking as closed.

G
