### ISSUE TITLE
Cannot double click to start drawing with a single quote in the page name

### ISSUE THREAD

**Issue by ovhk** [mikitex70/redmine_drawio#91]
Create a page with a single quote in the title : Tot'o

insert {{drawio_attach(toto_1.png)}}

You will not be able to double click on the button "double click to start drawing"

Thanks for your help (and plug'in !)

**Comment by mikitex70** [comment]
Hi @ovhk, I've fixed the bug in the `develop` branch.
I will released it as soon as possible, as soon as I have also fixed bug #92, very similar to this one.

**Comment by mikitex70** [comment]
The fix is now released in the `v1.0.2` release.
Thanks for reporting this issue @ovhk, it could be a security issue.
