### ISSUE TITLE
"Double Click to Start Drawing" button doesn't work

### ISSUE THREAD

**Issue by naimulhq** [mikitex70/redmine_drawio#97]
I have installed the plugin on EasyRedmine. I have an existing project and I wanted to add a Diagram in the Wiki tab. I would create a new entry and add the following: `{{drawio_attach(myDiagram)}}` and save it on the Wiki. The button would show up but nothing happens when I double click the button. The button does not redirect me to the other page.

**Comment by mikitex70** [comment]
Hi @naimulhq, try i press the key F12 and look in the `Console` tab if there is some error.
EasyReadmine is a commercial product and I cannot test on it, I can only test on the free version of Redmine.
Also can you tell me what version of the drawio plugin are you using?

**Comment by naimulhq** [comment]
I was able to get the button to work. I just removed and reinstall the plugin. However, when I click on the button, it says that "SSL received a record that exceeded the maximum permissible length.

Error code: SSL_ERROR_RX_RECORD_TOO_LONG"

The console does not show any output

**Comment by naimulhq** [comment]
I figured out it is because when I click the button, it is redirecting me to my local instance of drawio but by using HTTPS instead of HTTP.

**Comment by mikitex70** [comment]
In the plugin configuration dialog explicitly set the protocol to http for your internal drawio instance.
Also keep in mind that it's not possible to use HTTP resources from an HTTPS site. You have two solutions:
1. expose the Redmine site wiith the HTTP protocol
1. expose the local Drawio site with the HTTPS protocol.

**Comment by mikitex70** [comment]
No more feedback, closing this issue.
