### ISSUE TITLE
Cannot double click to start drawing with a single quote in the page name

### ISSUE THREAD

**Issue by ovhk** [mikitex70/redmine_drawio#98]
It looks like special chars in the page name again : ' #91 

Console : `Uncaught SyntaxError: missing ) after argument list`

HTML generated :

`<p><img alt="Diagram.png" title="Double click to edit diagram" class="drawioDiagram" style="cursor:pointer;" ondblclick="editDiagram(this,&#39;Processus_1.png&#39;, false, &#39;Gestion_de_l&#39;obsolescence&#39;);" src="data:image/png;charset=utf-8;base64,xxx" /></p>`

**Comment by mikitex70** [comment]
Hi @ovhk, I've fixed the issue.
Thanks for reporting it.

**Comment by mikitex70** [comment]
Hi @ovhk, I've fixed the issue.
Thanks for reporting it.
